services:
  mongodb:
    image: mongo:latest
    container_name: url_shortener_mongodb
    ports:
      - published: 27017
        target: 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db

  mongo-express:
    image: mongo-express:latest
    container_name: url_shortener_mongo_express
    ports:
      - published: 8081
        target: 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
    depends_on:
      mongodb:
        condition: service_started

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: url_shortener_server
    ports:
      - published: 5001
        target: 5000
    environment:
      NODE_ENV: development
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGODB_HOST: mongodb
      PORT: 5000
      BASEURI: http://localhost:5001
    depends_on:
      mongodb:
        condition: service_started

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: url_shortener_client
    ports:
      - published: 4173
        target: 4173
    environment:
      VITE_APP_URI: http://localhost:5001
    depends_on:
      server:
        condition: service_started

volumes:
  mongodb_data:
    name: url_shortener_mongodb_data
