apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-shortener.fullname" . }}-config
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.server.env.NODE_ENV | quote }}
  PORT: "5000"
  MONGODB_HOST: {{ include "url-shortener.fullname" . }}-mongo
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: {{ .Values.mongodb.auth.database | quote }}
  # Generate appropriate backend URL based on deployment type
  {{- if .Values.networking.useIngress }}
  BACKEND_PUBLIC_URL: {{ printf "http://%s" (index .Values.networking.ingress.hosts 0).host | quote }}
  {{- else }}
  BACKEND_PUBLIC_URL: {{ printf "http://%s:%d" .Values.externalAccessHost (int .Values.server.service.nodePort) | quote }}
  {{- end }}
