apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "url-shortener.fullname" . }}-server
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "url-shortener.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "url-shortener.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: server
          image: {{ include "url-shortener.serverImage" . | quote }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.server.env.NODE_ENV | quote }}
            - name: PORT
              value: "5000"
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.auth.rootUsername | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.auth.rootPassword | quote }}
            - name: MONGODB_HOST
              value: {{ include "url-shortener.fullname" . }}-mongo
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.auth.database | quote }}
            - name: BASEURI
              {{- if .Values.networking.useIngress }}
              value: {{ printf "http://%s" (index .Values.networking.ingress.hosts 0).host | quote }}
              {{- else }}
              value: {{ printf "http://%s-server:%d" (include "url-shortener.fullname" .) (int .Values.server.service.port) | quote }}
              {{- end }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
