apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.auth.existingSecret }}
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.mongodb.auth.userKey }}: {{ .Values.mongodb.auth.username | b64enc }}
  {{ .Values.mongodb.auth.passwordKey }}: {{ .Values.mongodb.auth.password | b64enc }}