{{- if not .Values.mongodb.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}-mongodb-credentials
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-root-username: {{ .Values.mongodb.auth.rootUser | default "admin" | quote }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | default "password" | quote }}
{{- end -}}