{{- if .Values.mongodb.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "url-shortener.fullname" . }}-mongodb
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | default "1Gi" }}
{{- end -}}