apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}-mongodb-secret
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUsername | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
