apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-client
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ if .Values.networking.useIngress }}ClusterIP{{ else }}{{ .Values.client.service.type }}{{ end }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: 4173
      protocol: TCP
      name: http
      {{- if and (not .Values.networking.useIngress) (eq .Values.client.service.type "NodePort") }}
      nodePort: {{ .Values.client.service.nodePort }}
      {{- end }}
  selector:
    {{- include "url-shortener.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client
