apiVersion: v1
kind: Service
metadata:
  name: {{ include "url-shortener.fullname" . }}-server
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "url-shortener.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server