# Default values for url-shortener
global:
  environment: production

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: "6.0"
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 10Gi
  auth:
    existingSecret: mongodb-credentials
    userKey: mongo_root_username
    passwordKey: mongo_root_password

server:
  image:
    repository: ghcr.io/nova-iris/url-shortener/server
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 5000
  ingress:
    enabled: false
  env:
    NODE_ENV: production
  healthcheck:
    enabled: true
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 3
    failureThreshold: 3

client:
  image:
    repository: ghcr.io/nova-iris/url-shortener/client
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 4173
  ingress:
    enabled: false
    className: nginx
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
  env:
    VITE_APP_URI: http://server:5000