name: CI/CD - Develop branch

on:
  push:
    branches: [develop]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  ENV: develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [client, server]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./src/${{ matrix.component }}
          file: ./src/${{ matrix.component }}/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.ENV }}/${{ matrix.component }}:${{ env.ENV }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.ENV }}/${{ matrix.component }}:${{ github.sha }}

  # notify:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Notify
  #       run: |
  #         echo "Deployment to staging complete!"
  #         # Add Slack, Discord, or GitHub comment notification here 