name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ github.repository }}/client
          ghcr.io/${{ github.repository }}/server

    - name: Build and push client image
      uses: docker/build-push-action@v4
      with:
        context: ./client
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/client:${{ github.ref_name }}
          ghcr.io/${{ github.repository }}/client:latest

    - name: Build and push server image
      uses: docker/build-push-action@v4
      with:
        context: ./server
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/server:${{ github.ref_name }}
          ghcr.io/${{ github.repository }}/server:latest

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true